# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-09-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_DefaultBuyPriceIzZero'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='need_remind',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
